from os.path import join

include: join("rules/init.smk")
include: join("rules/rsem.smk")
include: join("rules/star.smk")
include: join("rules/rmats.smk")
include: join("rules/isa.smk")

localrules: all

rule all:
    input:
        # create star index
        # join(STARINDEXDIR,"SA"),
        # create rsem index
        join(RSEMINDEXDIR,"ref.transcripts.ump"),
        join(RSEMINDEXDIR,"ref.bed12"),
        # create index if needed
        join(STARINDEXDIR,"SA"),
        # run STAR
        expand(join(BAMDIR,"{sample}.Aligned.sortedByCoord.out.bam"),sample=SAMPLES),
        expand(join(BAMDIR,"{sample}.Aligned.toTranscriptome.out.bam"),sample=SAMPLES),
        # rsem counts
        expand(join(WORKDIR,"rsem","isoformcounts","{sample}","{sample}.RSEM.isoform.results"),sample=SAMPLES),
        # rmats output
        # expand(join(RESULTSDIR,"{contrast}","rmats","summary.txt"),contrast=CONTRASTS)
        # IsoformSwitchAnalyzeR output
        #expand(join(RESULTSDIR,"{contrast}","isa","SplicingSummary.pdf"),contrast=CONTRASTS))
	
