from os.path import join

include: join("rules/init.smk")
include: join("rules/rsem.smk")
include: join("rules/rmats.smk")

localrules: all

rule all:
    input:
        # create star index
        # join(STARINDEXDIR,"SA"),
        # create rsem index
        join(RSEMINDEXDIR,"ref.transcripts.ump")
        # rmats output
        # expand(join(RESULTSDIR,"{contrast}","summary.txt"),contrast=CONTRASTS)
	
