from os.path import join

include: join("rules/init.smk")
include: join("rules/rmats.smk")

localrules: all

rule all:
    input:
        # create index if needed
        join(STARINDEXDIR,"SA"),
        # rmats output
        expand(join(RESULTSDIR,"{contrast}","summary.txt"),contrast=CONTRASTS)
	
